hobby_list = [
  "Reading",
  "Writing",
  "Drawing",
  "Painting",
  "Sculpting",
  "Photography",
  "Playing an Instrument",
  "Singing",
  "Dancing",
  "Acting",
  "Cooking",
  "Baking",
  "Gardening",
  "Knitting",
  "Crocheting",
  "Sewing",
  "Woodworking",
  "Metalworking",
  "Pottery",
  "Calligraphy",
  "Origami",
  "Magic Tricks",
  "Chess",
  "Board Games",
  "Video Games",
  "Card Games",
  "Puzzles",
  "Running",
  "Cycling",
  "Swimming",
  "Hiking",
  "Rock Climbing",
  "Yoga",
  "Meditation",
  "Pilates",
  "Weightlifting",
  "Martial Arts",
  "Boxing",
  "Wrestling",
  "Fencing",
  "Archery",
  "Golf",
  "Tennis",
  "Badminton",
  "Table Tennis",
  "Basketball",
  "Football",
  "Soccer",
  "Volleyball",
  "Rugby",
  "Cricket",
  "Baseball",
  "Softball",
  "Ice Hockey",
  "Figure Skating",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Skateboarding",
  "Parkour",
  "Diving",
  "Skydiving",
  "Bungee Jumping",
  "Paragliding",
  "Sailing",
  "Kayaking",
  "Canoeing",
  "Rafting",
  "Fishing",
  "Scuba Diving",
  "Snorkeling",
  "Bird Watching",
  "Star Gazing",
  "Meteorology",
  "Astronomy",
  "Geocaching",
  "Foraging",
  "Herpetology",
  "Entomology",
  "Botany",
  "Ornithology",
  "Astrophotography",
  "Stargazing",
  "Philately",
  "Numismatics",
  "Antiquing",
  "Collecting",
  "Genealogy",
  "Linguistics",
  "Etymology",
  "Conlanging",
  "Cryptocurrency Trading",
  "Stock Trading",
  "Investing",
  "Finance",
  "Economics",
  "Business",
  "Entrepreneurship",
  "Marketing",
  "Advertising",
  "Public Relations",
  "Event Planning",
  "Project Management",
  "Human Resources",
  "Customer Service",
  "Sales",
  "Retail",
  "Hospitality",
  "Travel",
  "Tourism",
  "Culinary Tourism",
  "Cultural Tourism",
  "Adventure Tourism",
  "Ecotourism",
  "Medical Tourism",
  "Volunteer Tourism",
  "Space Tourism",
  "Fashion Design",
  "Fashion Illustration",
  "Fashion Styling",
  "Fashion Photography",
  "Pattern Making",
  "Sustainable Fashion",
  "Interior Design",
  "Architecture",
  "Landscape Architecture",
  "Urban Planning",
  "Graphic Design",
  "Web Design",
  "UI/UX Design",
  "Animation",
  "Game Design",
  "Product Design",
  "Industrial Design",
  "Automotive Design",
  "Furniture Design",
  "Jewelry Design",
  "Toy Design",
  "Package Design",
  "Photography",
  "Digital Art",
  "Illustration",
  "Cartooning",
  "Comic Book Art",
  "Storyboarding",
  "Typography",
  "Calligraphy",
  "Printing",
  "Bookbinding",
  "Paper Making",
  "Scrapbooking",
  "Quilting",
  "Candle Making",
  "Soap Making",
  "Cosmetic Making",
  "Perfume Making",
  "Brewing",
  "Wine Making",
  "Mixology",
  "Cocktail Making",
  "Coffee Roasting",
  "Tea Blending",
  "Beekeeping",
  "Farming",
  "Agriculture",
  "Horticulture",
  "Aquaculture",
  "Forestry",
  "Wildlife Conservation",
  "Environmentalism",
  "Recycling",
  "Upcycling",
  "Composting",
  "Renewable Energy",
  "Solar Energy",
  "Wind Energy",
  "Hydropower",
  "Geothermal Energy",
  "Nuclear Energy",
  "Space Exploration",
  "Rocketry",
  "Astronomy",
  "Astrophysics",
  "Cosmology",
  "Particle Physics",
  "Quantum Physics",
  "Nanotechnology",
  "Biotechnology",
  "Genetic Engineering",
  "Cloning",
  "Bioinformatics",
  "Neuroscience",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Archaeology",
  "History",
  "Political Science",
  "International Relations",
  "Geography",
  "Philosophy",
  "Ethics",
  "Logic",
  "Aesthetics",
  "Theology",
  "Comparative Religion",
  "Mythology",
  "Folklore",
  "Literature",
  "Poetry",
  "Prose",
  "Drama",
  "Screenwriting",
  "Playwriting",
  "Novel Writing",
  "Short Story Writing",
  "Journalism",
  "Editing",
  "Proofreading",
  "Translation",
  "Transcription",
  "Copywriting",
  "Content Writing",
  "Technical Writing",
  "Grant Writing",
  "Blogging",
  "Podcasting",
  "Vlogging",
  "YouTube",
  "Twitch",
  "Social Media",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Analytics",
  "Big Data",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Robotics",
  "Automation",
  "Internet of Things",
  "Blockchain",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Digital Forensics",
  "Cloud Computing",
  "DevOps",
  "System Administration",
  "Network Administration",
  "Database Administration",
  "Software Development",
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Embedded Systems",
  "Augmented Reality",
  "Virtual Reality",
  "3D Printing",
  "Robotics",
  "Drone Piloting",
  "DIY Projects",
  "Home Improvement",
  "Car Mechanics",
  "Motorcycle Mechanics",
  "Bicycle Mechanics",
  "Electronics",
  "Arduino",
  "Raspberry Pi",
  "Computer Building",
  "PC Gaming",
  "Console Gaming",
  "Retro Gaming",
  "Board Game Design",
  "Card Game Design",
  "Puzzle Design",
  "Toy Design",
  "Model Making",
  "Miniature Painting",
  "Cosplay",
  "LARPing",
  "Magic: The Gathering",
  "Astrology",
  "Tarot Reading",
  "Palmistry",
  "Numerology",
  "Crystal Healing",
  "Reiki",
  "Yoga",
  "Meditation",
  "Mindfulness",
  "Tai Chi",
  "Qi Gong",
  "Acupuncture",
  "Herbalism",
  "Aromatherapy",
  "Holistic Health",
  "Ayurveda",
  "Homeopathy",
  "Naturopathy",
  "Reflexology",
  "Massage Therapy",
  "Chiropractic Care",
  "Physical Therapy",
  "Occupational Therapy",
  "Speech Therapy",
  "Music Therapy",
  "Animal Assisted Therapy",
  "Art Therapy",
  "Drama Therapy",
  "Dance Therapy",
  "Somatic Therapy",
  "Psychodrama",
  "Gestalt Therapy",
  "Cognitive Behavioral Therapy",
  "Psychoanalysis",
  "Jungian Analysis",
  "Existential Therapy",
  "Humanistic Therapy",
  "Transpersonal Psychology",
  "Positive Psychology",
  "Child Psychology",
  "Adolescent Psychology",
  "Adult Psychology",
  "Geriatric Psychology",
  "Forensic Psychology",
  "Sports Psychology",
  "Health Psychology",
  "Clinical Psychology",
  "Counseling Psychology",
  "Educational Psychology",
  "Industrial-Organizational Psychology",
  "Environmental Psychology",
  "Community Psychology",
  "Political Psychology",
  "Media Psychology",
  "Developmental Psychology",
  "Social Psychology",
  "Cognitive Psychology",
  "Biopsychology",
  "Neuropsychology",
  "Evolutionary Psychology",
  "Comparative Psychology",
  "Clinical Social Work",
  "Community Social Work",
  "Medical Social Work",
  "School Social Work",
  "Criminal Justice Social Work",
  "Military Social Work",
  "International Social Work",
  "Policy Social Work",
  "Research Social Work",
  "Advocacy Social Work",
  "Human Rights Social Work",
  "Animal Rights Advocacy",
  "Environmental Advocacy",
  "Social Justice Advocacy",
  "Racial Justice Advocacy",
  "Gender Equality Advocacy",
  "LGBTQ+ Advocacy",
  "Disability Rights Advocacy",
  "Immigrant Rights Advocacy",
  "Veterans Rights Advocacy",
  "Children's Rights Advocacy",
  "Elder Rights Advocacy",
  "Humanitarian Aid",
  "Disaster Relief",
  "Refugee Support",
  "Community Development",
  "International Development",
  "Social Entrepreneurship",
  "Microfinance",
  "Fair Trade",
  "Sustainability",
  "Corporate Social Responsibility",
  "Ethical Investing",
  "Green Living",
  "Minimalism",
  "Zero Waste Lifestyle",
  "Veganism",
  "Vegetarianism",
  "Plant-Based Diet",
  "Organic Farming",
  "Permaculture",
  "Beekeeping",
  "Community Gardens",
  "Food Security",
  "Food Sovereignty",
  "Food Justice",
  "Public Health",
  "Epidemiology",
  "Health Education",
  "Health Promotion",
  "Health Advocacy",
  "Health Policy",
  "Global Health",
  "Maternal and Child Health",
  "Reproductive Health",
  "Sexual Health",
  "Mental Health",
  "Substance Abuse Counseling",
  "Addiction Recovery",
  "Gambling Addiction Counseling",
  "Eating Disorders Counseling",
  "Body Image Counseling",
  "Trauma Counseling",
  "PTSD Counseling",
  "Grief Counseling",
  "Bereavement Counseling",
  "Crisis Intervention",
  "Suicide Prevention",
  "Domestic Violence Counseling",
  "Child Abuse Counseling",
  "Family Therapy",
  "Marriage Counseling",
  "Divorce Counseling",
  "Parenting Classes",
  "Childbirth Education",
  "Breastfeeding Support",
  "Infant Care Classes",
  "Child Development Classes",
  "Parenting Support Groups",
  "Single Parent Support Groups",
  "Adoption Support Groups",
  "Foster Care Support Groups",
  "Special Needs Parenting Support Groups",
  "Alzheimer's Support Groups",
  "Cancer Support Groups",
  "Chronic Illness Support Groups",
  "Disability Support Groups",
  "Mental Health Support Groups",
  "Substance Abuse Support Groups",
  "Grief Support Groups",
  "Bereavement Support Groups",
  "Divorce Support Groups",
  "Domestic Violence Support Groups",
  "LGBTQ+ Support Groups",
  "Teen Support Groups",
  "Women's Support Groups",
  "Men's Support Groups",
  "Seniors' Support Groups",
  "Veterans' Support Groups",
  "Hiking",
  "Rock Climbing",
  "Mountaineering",
  "Caving",
  "Canopying",
  "Ziplining",
  "Parasailing",
  "Paragliding",
  "Hang Gliding",
  "Skydiving",
  "Bungee Jumping",
  "White Water Rafting",
  "Kayaking",
  "Canoeing",
  "Sailing",
  "Scuba Diving",
  "Snorkeling",
  "Surfing",
  "Bodyboarding",
  "Wakeboarding",
  "Kiteboarding",
  "Windsurfing",
  "Skiing",
  "Snowboarding",
  "Cross-Country Skiing",
  "Snowshoeing",
  "Dog Sledding",
  "Ice Climbing",
  "Ice Fishing",
  "Ice Skating",
  "Figure Skating",
  "Speed Skating",
  "Curling",
  "Bobsledding",
  "Luge",
  "Skeleton",
  "Street Hockey",
  "Ice Hockey",
  "Field Hockey",
  "Roller Hockey",
  "Floorball",
  "Shinty",
  "Bandy",
  "Cricket",
  "Baseball",
  "Softball",
  "Tee Ball",
  "Rounders",
  "Stoolball",
  "Kickball",
  "Rugby",
  "Rugby Sevens",
  "Rugby League",
  "Rugby Union",
  "Australian Rules Football",
  "American Football",
  "Canadian Football",
  "Flag Football",
  "Touch Football",
  "Beach Soccer",
  "Futsal",
  "Freestyle Football",
  "Soccer Tennis",
  "Footvolley",
  "Sepak Takraw",
  "Juggling",
  "Cycling",
  "Mountain Biking",
  "Road Cycling",
  "BMX",
  "Track Cycling",
  "Cyclocross",
  "Freestyle BMX",
  "Dirt Jumping",
  "Flatland BMX",
  "Vert BMX",
  "Trials Riding",
  "Motorcycle Racing",
  "Motocross",
  "Motorsport",
  "Formula One",
  "NASCAR",
  "IndyCar",
  "Drag Racing",
  "Rally Racing",
  "Superbike Racing",
  "Motorcycle Trials",
  "Freestyle Motocross",
  "Supermoto",
  "Street Racing",
  "Drifting",
  "Autocross",
  "Rallycross",
  "Time Attack",
  "Truck Racing",
  "Off-Road Racing",
  "Monster Truck Racing",
  "Mud Bogging",
  "Rock Crawling",
  "Trail Riding",
  "Trials Riding",
  "Mountain Boarding",
  "Sandboarding",
  "Skateboarding",
  "Longboarding",
  "Cruiser Boarding",
  "Freestyle Skateboarding",
  "Vert Skateboarding",
  "Street Skateboarding",
  "Slalom Skateboarding",
  "Downhill Skateboarding",
  "Roller Skating",
  "Inline Skating",
  "Roller Derby",
  "Freestyle Roller Skating",
  "Artistic Roller Skating",
  "Speed Skating",
  "Ice Skating",
  "Figure Skating",
  "Speed Skating",
  "Short Track Speed Skating",
  "Synchronized Skating",
  "Ice Dancing",
  "Curling",
  "Cycling",
  "Road Cycling",
  "Mountain Biking",
  "BMX",
  "Freestyle BMX",
  "Flatland BMX",
  "Street BMX",
  "Dirt Jumping",
  "Downhill Mountain Biking",
  "Cross-Country Mountain Biking",
  "Cycle Speedway",
  "Track Cycling",
  "Cyclo-cross",
  "Bike Trials",
  "Artistic Cycling",
  "Racing",
  "Track Racing",
  "Criterium Racing",
  "Road Racing",
  "Stage Racing",
  "Time Trialing",
  "Hill Climbing",
  "Gravel Racing",
  "Gravel Grinding",
  "Adventure Racing",
  "Mountain Racing",
  "Obstacle Course Racing",
  "Triathlon",
  "Ironman",
  "Ultramarathon",
  "Trail Running",
  "Mountain Running",
  "Skyrunning",
  "Obstacle Course Racing",
  "Adventure Racing",
  "Parkour",
  "Freerunning",
  "Tricking",
  "Bouldering",
  "Sport Climbing",
  "Traditional Climbing",
  "Lead Climbing",
  "Top Rope Climbing",
  "Ice Climbing",
  "Mountaineering",
  "Alpine Climbing",
  "Big Wall Climbing",
  "Free Solo Climbing",
  "Aid Climbing",
  "Trad Climbing",
  "Speed Climbing",
  "Waterfall Climbing",
  "Tree Climbing",
  "Rope Climbing",
  "Rock Climbing",
  "Indoor Climbing",
  "Outdoor Climbing",
  "Deep-water Soloing",
  "Ice Climbing",
  "Mixed Climbing",
  "Dry-tooling",
  "Traditional Climbing",
  "Sport Climbing",
  "Bouldering",
  "Buildering",
  "Canyoning",
  "Coasteering",
  "Pot-holing",
  "Rappelling",
  "Speleology",
  "Spelunking",
  "Free Diving",
  "Spearfishing",
  "Freediving",
  "Scuba Diving",
  "Technical Diving",
  "Recreational Diving",
  "Cave Diving",
  "Wreck Diving",
  "Ice Diving",
  "Deep Diving",
  "Shark Diving",
  "Whale Diving",
  "Ray Diving",
  "Dolphin Diving",
  "Seal Diving",
  "Turtle Diving",
  "Octopus Diving",
  "Jellyfish Diving",
  "Squid Diving",
  "Cuttlefish Diving",
  "Lobster Diving",
  "Crab Diving",
  "Shrimp Diving",
  "Fish Diving",
  "Coral Diving",
  "Kelp Diving",
  "Seagrass Diving",
  "Eelgrass Diving",
  "Mangrove Diving",
  "Rainforest Diving",
  "Marsh Diving",
  "Swamp Diving",
  "Bog Diving",
  "Pond Diving",
  "Lake Diving",
  "River Diving",
  "Stream Diving",
  "Waterfall Diving",
  "Spring Diving",
  "Glacier Diving",
  "Iceberg Diving",
  "Arctic Diving",
  "Antarctic Diving",
  "Ocean Diving",
  "Sea Diving",
  "Gulf Diving",
  "Bay Diving",
  "Cove Diving",
  "Fjord Diving",
  "Estuary Diving",
  "Delta Diving",
  "Lagoon Diving",
  "Atoll Diving",
  "Island Diving",
  "Continental Shelf Diving",
  "Seamount Diving",
  "Ocean Trench Diving",
  "Kite Surfing",
  "Wind Surfing",
  "Hydrofoil Surfing",
  "Skimboarding",
  "Bodyboarding",
  "Riverboarding",
  "Sandboarding",
  "Snowboarding",
  "Wakeboarding",
  "Wakeskating",
  "Wakesurfing",
  "Water Skiing",
  "Kneeboarding",
  "Parasailing",
  "Paragliding",
  "Hang Gliding",
  "Base Jumping",
  "Wingsuit Flying",
  "Skydiving",
  "Bungee Jumping",
  "Cliff Diving",
  "Canyon Swinging",
  "Slacklining",
  "Highlining",
  "Waterlining",
  "Longlining",
  "Rodeo Riding",
  "Bull Riding",
  "Bronc Riding",
  "Steer Wrestling",
  "Team Roping",
  "Tie-down Roping",
  "Barrel Racing",
  "Pole Bending",
  "Goat Tying",
  "Cutting",
  "Reining",
  "Ranch Sorting",
  "Campdrafting",
  "Show Jumping",
  "Horse Racing",
  "Harness Racing",
  "Steeplechase",
  "Endurance Riding",
  "Pleasure Riding",
  "Trail Riding",
  "Thoroughbred Racing",
  "Quarter Horse Racing",
  "Arabian Horse Racing",
  "Standardbred Racing",
  "Appaloosa Racing",
  "Paint Horse Racing",
  "Polo",
  "Polo Cross",
  "Mounted Games",
  "Horseball",
  "Vaulting",
  "Tent Pegging",
  "Charreada",
  "Jousting",
  "Medieval Reenactment",
  "Renaissance Faire",
  "Living History",
  "Historical European Martial Arts",
  "Blacksmithing",
  "Leatherworking",
  "Woodworking",
];
