name: Lint
on:
  push:
  pull_request:
env:
  NODE_VERSION: 16
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: .
        run: npm ci
      - name: ESLint
        working-directory: .
        run: npm run lint
